### ISSUE TITLE
Why a fixed list of supported PDO driver?

### ISSUE THREAD

**Issue by mfprimo** [fab2s/YaEtl#5]
Hi,
  I don't understand the reason why PDOExtector check the PDO driver and refuse all except 'mysql', 'sqlite' and 'pgsql'.
Looking at the code, I do not find anything which prevent other drivers to be used.
I need to connect a Oracle database using a custum, but fully compliant, PDO driver.

**Comment by fab2s** [comment]
Hello, 

There are two spots that could cause problem as they are not really driver agnostic:
https://github.com/fab2s/YaEtl/blob/master/src/Extractors/DbExtractorAbstract.php#L142

```php
    /**
     * Build the LIMIT...OFFSET bit of the query
     *
     * @return string
     */
    protected function getLimitOffsetBit(): string
    {
        return ' ' . \implode('', [
            ' LIMIT ' . (int) $this->batchSize,
            $this->offset ? ' OFFSET ' . (int) $this->offset : '',
        ]);
    }
```

and: 
https://github.com/fab2s/YaEtl/blob/master/src/Extractors/PdoUniqueKeyExtractor.php#L109
```php
    /**
     * This method sets offset and limit in the query
     * WARNING : if you set an offset without limit,
     * the limit will be set to  $this->maxdefaultLimit
     *
     * @return string the paginated query with current offset and limit
     */
    protected function getPaginatedQuery(): string
    {
        if ($this->joinFrom) {
            $this->queryBindings = array_values($this->uniqueKeyValues);

            $whereOrAndStr = stripos($this->extractQuery, 'WHERE') !== false ? 'AND' : 'WHERE';

            return $this->extractQuery . " $whereOrAndStr $this->uniqueKeyName IN (" . implode(',', array_fill(0, count($this->uniqueKeyValues), '?')) . ')';
        }

        return $this->extractQuery . $this->getLimitOffsetBit();
    }
```

They should be ok with more drivers, but since that's also kind of a design issue at the moment, will move them around in v2.

Now, it's easy to extend, since all extractors inheriting from the `pdo` branch do carry `PdoExtractorTrait`, you can just extend the one you use and add more entries in the `$supportedDrivers` property:
```php
    /**
     * List of supported drivers
     *
     * @var array
     */
    protected $supportedDrivers = [
        'mysql'  => 'mysql',
        'sqlite' => 'sqlite',
        'pgsql'  => 'pgsql',
    ];
```

Doing this should solve your current concern, as long as the two above method don't mess up, but, you can always overload them in your extractor (if so, thank you for sharing your findings).

**Comment by mfprimo** [comment]
Hi,
  yes I already saw the point and I've already tried to implement an extractor for backends which don't support pagination, but I'm confused: why I have to implement ExtractorInterface when extract() is never called from outside the implementing class itself? I miss something or is a debris of an old architecture?

**Comment by fab2s** [comment]
Concrete implementations do inherit from a cascade of abstract that are intended to branch the logic at a higher level, should it be necessary (some extractor do not paginate, others can't have a limit etc ...) like it is the case for file extraction.

About pagination branching occurs after `ExtractorLimitAbstract`, which only set support for backbends supporting a limit in the number of records you can request at once, or even above in `ExtractorAbstract`, the beginning of the pagination logic is added in `ExtractorBatchLimitAbstract`.

Though, DBMS should be able to somehow paginate queries, and you should be able to either tweak the `getPaginatedQuery` method in your class and do what's necessary (you really just need to write the proper query to include limit and offset, which are already set properly before).

Laravel flavor of the db extractor could provide with more compatibility since they use its db driver, worth a try too.
